import express from 'express';
import cors from 'cors';
import https from 'https';
import { projectsRouter } from './api/projects.js';
import { gitRouter } from './api/git.js';
import { githubRouter } from './api/github.js';
import { settingsRouter } from './api/settings.js';
import { runnerRouter, cleanupAllRunningProjects, getRunnerHealth } from './api/runner.js';
import { aiRouter } from './api/ai.js';
import compression from 'compression';
import { apiLimiter, aiLimiter, rejectLargeJsonRequests, requestLogger, securityHeaders, validateRequest } from './middleware/security.js';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';
import { generateSelfSignedCert } from './utils/ssl.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = Number(process.env.SERVER_PORT) || 3101;

// Ensure projects directory exists
const PROJECTS_DIR = path.join(__dirname, '../projects');
if (!fs.existsSync(PROJECTS_DIR)) {
  fs.mkdirSync(PROJECTS_DIR, { recursive: true });
}

// Security headers (helmet)
app.use(securityHeaders);

// Compress API responses (gzip/brotli)
app.use(compression());

// VF-04 fix: Removed runner ports (3300-3399) from CORS allowlist
// Runner pages generated by AI cannot make authenticated API requests
// Credentials are only allowed for main FluidFlow ports
app.use(cors({
  origin: (origin, callback) => {
    // Allow requests with no origin (mobile apps, curl, etc)
    if (!origin) return callback(null, true);

    // Allow localhost ports: 3100-3102 (FluidFlow), 5173 (Vite dev)
    // Runner ports (3300-3399) removed - AI-generated pages must not access API with credentials
    const allowedPatterns = [
      /^https?:\/\/localhost:(3100|3101|3102|5173)$/,
    ];

    const isAllowed = allowedPatterns.some(pattern => pattern.test(origin));
    callback(null, isAllowed);
  },
  credentials: true
}));
// Rate limiting for all API endpoints (100 requests per 15 minutes)
app.use('/api', apiLimiter);
app.use('/api', rejectLargeJsonRequests);

app.use(express.json({ limit: '50mb' }));

// Request validation (block suspicious patterns)
app.use('/api', validateRequest);

// Request logging (development only)
if (process.env.NODE_ENV !== 'production') {
  app.use(requestLogger);
}

// Health check with runner status
app.get('/api/health', (req, res) => {
  const runnerHealth = getRunnerHealth();
  const memoryUsage = process.memoryUsage();

  res.json({
    status: 'ok',
    timestamp: Date.now(),
    uptime: process.uptime(),
    memory: {
      heapUsed: Math.round(memoryUsage.heapUsed / 1024 / 1024) + 'MB',
      heapTotal: Math.round(memoryUsage.heapTotal / 1024 / 1024) + 'MB',
      rss: Math.round(memoryUsage.rss / 1024 / 1024) + 'MB'
    },
    runner: runnerHealth
  });
});

// API Routes
app.use('/api/projects', projectsRouter);
app.use('/api/git', gitRouter);
app.use('/api/github', githubRouter);
app.use('/api/settings', settingsRouter);
app.use('/api/runner', runnerRouter);
app.use('/api/ai', aiLimiter, aiRouter); // FIX-06: Apply stricter rate limit to AI proxy

// Error handling middleware (must be after all routes)
app.use((err: Error, req: express.Request, res: express.Response, _next: express.NextFunction) => {
  console.error('[Server Error]', err);
  // SRV-001 fix: do not expose internal error details in production
  const isProduction = process.env.NODE_ENV === 'production';
  res.status(500).json({
    error: isProduction ? 'Internal server error' : (err.message || 'Internal server error')
  });
});

// SRV-001 fix: Global error handlers for uncaught errors
process.on('uncaughtException', (err) => {
  console.error('[Uncaught Exception]', err);
  // do not exit immediately to allow graceful handling of in-flight requests
});

process.on('unhandledRejection', (reason, promise) => {
  console.error('[Unhandled Rejection] at:', promise, 'reason:', reason);
});

// Generate SSL certificates for HTTPS
const sslCert = generateSelfSignedCert();

// VF-01 fix: Bind to localhost only by default to prevent LAN exposure
const HOST = process.env.SERVER_HOST || '127.0.0.1';

// Start HTTPS server
const server = https.createServer(sslCert, app).listen(PORT, HOST, () => {
  console.log(`\n🚀 FluidFlow Backend Server running on https://localhost:${PORT}`);
  console.log(`   Projects directory: ${PROJECTS_DIR}\n`);
});

// Graceful shutdown handler
let isShuttingDown = false;

async function gracefulShutdown(signal: string) {
  if (isShuttingDown) {
    console.log(`[Server] Already shutting down, ignoring ${signal}`);
    return;
  }
  isShuttingDown = true;

  console.log(`\n[Server] Received ${signal}, starting graceful shutdown...`);

  // Stop accepting new connections
  server.close(() => {
    console.log('[Server] HTTP server closed');
  });

  // Cleanup running projects
  try {
    const stopped = cleanupAllRunningProjects();
    console.log(`[Server] Cleaned up ${stopped} running projects`);
  } catch (err) {
    console.error('[Server] Error during project cleanup:', err);
  }

  // Give time for cleanup to complete
  setTimeout(() => {
    console.log('[Server] Shutdown complete');
    process.exit(0);
  }, 2000);
}

// Handle termination signals
process.on('SIGTERM', () => gracefulShutdown('SIGTERM'));
process.on('SIGINT', () => gracefulShutdown('SIGINT'));

// Handle Windows-specific close event
if (process.platform === 'win32') {
  process.on('SIGHUP', () => gracefulShutdown('SIGHUP'));
}

export { PROJECTS_DIR };
