/**
 * Import Mappings for Auto-Fix
 *
 * Centralized import source mappings for common React ecosystem packages.
 * Used by simpleFixes.ts for automatic import resolution.
 */

// Common React imports
export const REACT_IMPORTS: Record<string, string> = {
  'useState': 'react',
  'useEffect': 'react',
  'useCallback': 'react',
  'useMemo': 'react',
  'useRef': 'react',
  'useContext': 'react',
  'useReducer': 'react',
  'useLayoutEffect': 'react',
  'useImperativeHandle': 'react',
  'useDebugValue': 'react',
  'useDeferredValue': 'react',
  'useTransition': 'react',
  'useId': 'react',
  'useSyncExternalStore': 'react',
  'useInsertionEffect': 'react',
  'createContext': 'react',
  'Fragment': 'react',
  'Suspense': 'react',
  'lazy': 'react',
  'memo': 'react',
  'forwardRef': 'react',
  'createRef': 'react',
  'Component': 'react',
  'PureComponent': 'react',
  'StrictMode': 'react',
  'cloneElement': 'react',
  'isValidElement': 'react',
  'Children': 'react',
};

// Animation libraries
export const MOTION_IMPORTS: Record<string, string> = {
  'motion': 'motion/react',
  'AnimatePresence': 'motion/react',
  'useAnimation': 'motion/react',
  'useMotionValue': 'motion/react',
  'useTransform': 'motion/react',
  'useSpring': 'motion/react',
  'useScroll': 'motion/react',
  'useInView': 'motion/react',
  'useReducedMotion': 'motion/react',
  'MotionConfig': 'motion/react',
  'LazyMotion': 'motion/react',
  'domAnimation': 'motion/react',
  'domMax': 'motion/react',
  'Reorder': 'motion/react',
  'LayoutGroup': 'motion/react',
};

// State management libraries
export const STATE_MANAGEMENT_IMPORTS: Record<string, string> = {
  // Zustand
  'create': 'zustand',
  'createStore': 'zustand',
  'useStore': 'zustand',
  // TanStack Query
  'useQuery': '@tanstack/react-query',
  'useMutation': '@tanstack/react-query',
  'useQueryClient': '@tanstack/react-query',
  'QueryClient': '@tanstack/react-query',
  'QueryClientProvider': '@tanstack/react-query',
  'useInfiniteQuery': '@tanstack/react-query',
  'useSuspenseQuery': '@tanstack/react-query',
  // SWR
  'useSWR': 'swr',
  'useSWRConfig': 'swr',
  'SWRConfig': 'swr',
  // Jotai
  'atom': 'jotai',
  'useAtom': 'jotai',
  'useAtomValue': 'jotai',
  'useSetAtom': 'jotai',
  'Provider': 'jotai',
};

// Form libraries
export const FORM_IMPORTS: Record<string, string> = {
  // React Hook Form
  'useForm': 'react-hook-form',
  'useFieldArray': 'react-hook-form',
  'useWatch': 'react-hook-form',
  'useFormContext': 'react-hook-form',
  'FormProvider': 'react-hook-form',
  'Controller': 'react-hook-form',
  // Formik
  'Formik': 'formik',
  'Form': 'formik',
  'Field': 'formik',
  'ErrorMessage': 'formik',
  'useFormik': 'formik',
  // Zod
  'z': 'zod',
  'ZodError': 'zod',
};

// Routing libraries
export const ROUTING_IMPORTS: Record<string, string> = {
  // React Router v7
  'BrowserRouter': 'react-router',
  'Routes': 'react-router',
  'Route': 'react-router',
  'Link': 'react-router',
  'NavLink': 'react-router',
  'useNavigate': 'react-router',
  'useParams': 'react-router',
  'useSearchParams': 'react-router',
  'useLocation': 'react-router',
  'Outlet': 'react-router',
  'Navigate': 'react-router',
  'useRoutes': 'react-router',
  'useMatch': 'react-router',
};

// UI Component Libraries
export const UI_LIBRARY_IMPORTS: Record<string, string> = {
  // Radix UI primitives (commonly used with shadcn)
  'Dialog': '@radix-ui/react-dialog',
  'DialogTrigger': '@radix-ui/react-dialog',
  'DialogContent': '@radix-ui/react-dialog',
  'Popover': '@radix-ui/react-popover',
  'PopoverTrigger': '@radix-ui/react-popover',
  'PopoverContent': '@radix-ui/react-popover',
  'Tooltip': '@radix-ui/react-tooltip',
  'TooltipTrigger': '@radix-ui/react-tooltip',
  'TooltipContent': '@radix-ui/react-tooltip',
  'DropdownMenu': '@radix-ui/react-dropdown-menu',
  'Select': '@radix-ui/react-select',
  'Tabs': '@radix-ui/react-tabs',
  'Accordion': '@radix-ui/react-accordion',
  'Switch': '@radix-ui/react-switch',
  'Checkbox': '@radix-ui/react-checkbox',
  'RadioGroup': '@radix-ui/react-radio-group',
  'Slider': '@radix-ui/react-slider',
  'ScrollArea': '@radix-ui/react-scroll-area',
  // Headless UI
  'Menu': '@headlessui/react',
  'Listbox': '@headlessui/react',
  'Combobox': '@headlessui/react',
  'Transition': '@headlessui/react',
  'Disclosure': '@headlessui/react',
};

// Toast/Notification libraries
export const TOAST_IMPORTS: Record<string, string> = {
  // React Hot Toast
  'toast': 'react-hot-toast',
  'Toaster': 'react-hot-toast',
  // Sonner
  'Sonner': 'sonner',
  // React Toastify
  'ToastContainer': 'react-toastify',
  'cssTransition': 'react-toastify',
};

// Chart libraries
export const CHART_IMPORTS: Record<string, string> = {
  // Recharts
  'LineChart': 'recharts',
  'BarChart': 'recharts',
  'PieChart': 'recharts',
  'AreaChart': 'recharts',
  'XAxis': 'recharts',
  'YAxis': 'recharts',
  'CartesianGrid': 'recharts',
  'Legend': 'recharts',
  'ResponsiveContainer': 'recharts',
  'Line': 'recharts',
  'Bar': 'recharts',
  'Area': 'recharts',
  'Pie': 'recharts',
  'Cell': 'recharts',
  // Chart.js React wrapper
  'Chart': 'react-chartjs-2',
  'Doughnut': 'react-chartjs-2',
  'Radar': 'react-chartjs-2',
};

// Table libraries
export const TABLE_IMPORTS: Record<string, string> = {
  // TanStack Table
  'useReactTable': '@tanstack/react-table',
  'getCoreRowModel': '@tanstack/react-table',
  'getSortedRowModel': '@tanstack/react-table',
  'getFilteredRowModel': '@tanstack/react-table',
  'getPaginationRowModel': '@tanstack/react-table',
  'flexRender': '@tanstack/react-table',
  'createColumnHelper': '@tanstack/react-table',
};

// DnD (Drag and Drop) libraries
export const DND_IMPORTS: Record<string, string> = {
  // DnD Kit
  'DndContext': '@dnd-kit/core',
  'useDraggable': '@dnd-kit/core',
  'useDroppable': '@dnd-kit/core',
  'DragOverlay': '@dnd-kit/core',
  'closestCenter': '@dnd-kit/core',
  'SortableContext': '@dnd-kit/sortable',
  'useSortable': '@dnd-kit/sortable',
  'arrayMove': '@dnd-kit/sortable',
  // React DnD
  'useDrag': 'react-dnd',
  'useDrop': 'react-dnd',
  'DndProvider': 'react-dnd',
};

// Utility libraries
export const UTILITY_IMPORTS: Record<string, string> = {
  // clsx/classnames
  'clsx': 'clsx',
  'cx': 'clsx',
  'classNames': 'classnames',
  'cn': 'clsx', // commonly used alias - also check @/lib/utils
  // date-fns
  'format': 'date-fns',
  'parseISO': 'date-fns',
  'formatDistance': 'date-fns',
  'formatRelative': 'date-fns',
  'addDays': 'date-fns',
  'subDays': 'date-fns',
  'isValid': 'date-fns',
  'differenceInDays': 'date-fns',
  'startOfWeek': 'date-fns',
  'endOfWeek': 'date-fns',
  'isBefore': 'date-fns',
  'isAfter': 'date-fns',
  // lodash
  'debounce': 'lodash',
  'throttle': 'lodash',
  'cloneDeep': 'lodash',
  'isEmpty': 'lodash',
  'groupBy': 'lodash',
  'sortBy': 'lodash',
  'uniqBy': 'lodash',
  // axios
  'axios': 'axios',
  // uuid
  'v4': 'uuid',
  'uuidv4': 'uuid',
  // nanoid
  'nanoid': 'nanoid',
  // immer
  'produce': 'immer',
  'Draft': 'immer',
  // react-use hooks
  'useDebounce': 'react-use',
  'useThrottle': 'react-use',
  'useLocalStorage': 'react-use',
  'useWindowSize': 'react-use',
  'useMedia': 'react-use',
  'usePrevious': 'react-use',
  'useAsync': 'react-use',
  'useToggle': 'react-use',
  'useCopyToClipboard': 'react-use',
};

// Lucide React icons - comprehensive list
export const LUCIDE_ICONS: Record<string, string> = {
  // Common UI icons
  'Search': 'lucide-react',
  'X': 'lucide-react',
  'Check': 'lucide-react',
  'ChevronDown': 'lucide-react',
  'ChevronUp': 'lucide-react',
  'ChevronLeft': 'lucide-react',
  'ChevronRight': 'lucide-react',
  'Menu': 'lucide-react',
  'Plus': 'lucide-react',
  'Minus': 'lucide-react',
  'Edit': 'lucide-react',
  'Trash': 'lucide-react',
  'Trash2': 'lucide-react',
  'Save': 'lucide-react',
  'Download': 'lucide-react',
  'Upload': 'lucide-react',
  'Settings': 'lucide-react',
  'User': 'lucide-react',
  'Users': 'lucide-react',
  'Home': 'lucide-react',
  'Mail': 'lucide-react',
  'Phone': 'lucide-react',
  'Calendar': 'lucide-react',
  'Clock': 'lucide-react',
  'Star': 'lucide-react',
  'Heart': 'lucide-react',
  'Share': 'lucide-react',
  'Copy': 'lucide-react',
  'Link': 'lucide-react',
  'ExternalLink': 'lucide-react',
  'Eye': 'lucide-react',
  'EyeOff': 'lucide-react',
  'Lock': 'lucide-react',
  'Unlock': 'lucide-react',
  'Filter': 'lucide-react',
  'SortAsc': 'lucide-react',
  'SortDesc': 'lucide-react',
  'ArrowUp': 'lucide-react',
  'ArrowDown': 'lucide-react',
  'ArrowLeft': 'lucide-react',
  'ArrowRight': 'lucide-react',
  'RefreshCw': 'lucide-react',
  'Loader': 'lucide-react',
  'Loader2': 'lucide-react',
  // Alert/Status icons
  'AlertCircle': 'lucide-react',
  'AlertTriangle': 'lucide-react',
  'Info': 'lucide-react',
  'HelpCircle': 'lucide-react',
  'CheckCircle': 'lucide-react',
  'XCircle': 'lucide-react',
  'Bell': 'lucide-react',
  // Communication icons
  'MessageCircle': 'lucide-react',
  'Send': 'lucide-react',
  // File icons
  'Image': 'lucide-react',
  'File': 'lucide-react',
  'FileText': 'lucide-react',
  'Folder': 'lucide-react',
  'FolderOpen': 'lucide-react',
  'Database': 'lucide-react',
  'Server': 'lucide-react',
  // System icons
  'Cloud': 'lucide-react',
  'Wifi': 'lucide-react',
  'Bluetooth': 'lucide-react',
  'Battery': 'lucide-react',
  'Zap': 'lucide-react',
  'Sun': 'lucide-react',
  'Moon': 'lucide-react',
  // Navigation icons
  'Globe': 'lucide-react',
  'Map': 'lucide-react',
  'MapPin': 'lucide-react',
  'Navigation': 'lucide-react',
  'Compass': 'lucide-react',
  // Media icons
  'Camera': 'lucide-react',
  'Video': 'lucide-react',
  'Mic': 'lucide-react',
  'Volume': 'lucide-react',
  'Volume2': 'lucide-react',
  'VolumeX': 'lucide-react',
  'Play': 'lucide-react',
  'Pause': 'lucide-react',
  'Square': 'lucide-react',
  'Circle': 'lucide-react',
  'Triangle': 'lucide-react',
  'SkipBack': 'lucide-react',
  'SkipForward': 'lucide-react',
  'Rewind': 'lucide-react',
  'FastForward': 'lucide-react',
  'Shuffle': 'lucide-react',
  'Repeat': 'lucide-react',
  // Layout icons
  'MoreHorizontal': 'lucide-react',
  'MoreVertical': 'lucide-react',
  'Grid': 'lucide-react',
  'List': 'lucide-react',
  'Layout': 'lucide-react',
  'Sidebar': 'lucide-react',
  'Columns': 'lucide-react',
  'Rows': 'lucide-react',
  'Table': 'lucide-react',
  // Chart icons
  // Note: BarChart, LineChart, PieChart also exist in recharts
  'Activity': 'lucide-react',
  'TrendingUp': 'lucide-react',
  'TrendingDown': 'lucide-react',
  // Commerce icons
  'DollarSign': 'lucide-react',
  'CreditCard': 'lucide-react',
  'ShoppingCart': 'lucide-react',
  'ShoppingBag': 'lucide-react',
  'Package': 'lucide-react',
  'Gift': 'lucide-react',
  'Tag': 'lucide-react',
  'Bookmark': 'lucide-react',
  'Flag': 'lucide-react',
  'Award': 'lucide-react',
  'Trophy': 'lucide-react',
  'Target': 'lucide-react',
  'Crosshair': 'lucide-react',
  // Transform icons
  'Aperture': 'lucide-react',
  'Maximize': 'lucide-react',
  'Minimize': 'lucide-react',
  'Move': 'lucide-react',
  'Crop': 'lucide-react',
  'Scissors': 'lucide-react',
  // Clipboard icons
  'Clipboard': 'lucide-react',
  'ClipboardCheck': 'lucide-react',
  'ClipboardList': 'lucide-react',
  // Code icons
  'FileCode': 'lucide-react',
  'Terminal': 'lucide-react',
  'Code': 'lucide-react',
  'Code2': 'lucide-react',
  'Braces': 'lucide-react',
  'Hash': 'lucide-react',
  'AtSign': 'lucide-react',
  // Security icons
  'Key': 'lucide-react',
  'Shield': 'lucide-react',
  'ShieldCheck': 'lucide-react',
  'Fingerprint': 'lucide-react',
  'Scan': 'lucide-react',
  'QrCode': 'lucide-react',
  'Barcode': 'lucide-react',
  // Device icons
  'Printer': 'lucide-react',
  'Smartphone': 'lucide-react',
  'Tablet': 'lucide-react',
  'Monitor': 'lucide-react',
  'Laptop': 'lucide-react',
  'Tv': 'lucide-react',
  'Watch': 'lucide-react',
  'Headphones': 'lucide-react',
  'Speaker': 'lucide-react',
  'Radio': 'lucide-react',
  // Hardware icons
  'Cpu': 'lucide-react',
  'HardDrive': 'lucide-react',
  'MemoryStick': 'lucide-react',
  'Usb': 'lucide-react',
  // Toggle icons
  'Power': 'lucide-react',
  'PowerOff': 'lucide-react',
  'ToggleLeft': 'lucide-react',
  'ToggleRight': 'lucide-react',
  'Sliders': 'lucide-react',
  'SlidersHorizontal': 'lucide-react',
  // Gauge icons
  'Gauge': 'lucide-react',
  'Thermometer': 'lucide-react',
  // Weather icons
  'Droplet': 'lucide-react',
  'Wind': 'lucide-react',
  'Umbrella': 'lucide-react',
  'Snowflake': 'lucide-react',
  'Flame': 'lucide-react',
  // Nature icons
  'Leaf': 'lucide-react',
  'Tree': 'lucide-react',
  'Flower': 'lucide-react',
  'Bug': 'lucide-react',
  // Magic icons
  'Sparkles': 'lucide-react',
  'Wand': 'lucide-react',
  'Wand2': 'lucide-react',
  'Lightbulb': 'lucide-react',
  'Lamp': 'lucide-react',
  'Flashlight': 'lucide-react',
  // Professional icons
  'Glasses': 'lucide-react',
  'Briefcase': 'lucide-react',
  'Building': 'lucide-react',
  'Building2': 'lucide-react',
  'Factory': 'lucide-react',
  'Warehouse': 'lucide-react',
  'Store': 'lucide-react',
  'Landmark': 'lucide-react',
  'School': 'lucide-react',
  'GraduationCap': 'lucide-react',
  // Book icons
  'Book': 'lucide-react',
  'BookOpen': 'lucide-react',
  'Library': 'lucide-react',
  'Newspaper': 'lucide-react',
  'Rss': 'lucide-react',
  'Podcast': 'lucide-react',
  // Music icons
  'Music': 'lucide-react',
  'Music2': 'lucide-react',
  'Mic2': 'lucide-react',
  'Guitar': 'lucide-react',
  'Piano': 'lucide-react',
  'Drum': 'lucide-react',
  // Entertainment icons
  'Film': 'lucide-react',
  'Clapperboard': 'lucide-react',
  'Popcorn': 'lucide-react',
  'Gamepad': 'lucide-react',
  'Gamepad2': 'lucide-react',
  'Dice1': 'lucide-react',
  'Dice2': 'lucide-react',
  'Dice3': 'lucide-react',
  'Dice4': 'lucide-react',
  'Dice5': 'lucide-react',
  'Dice6': 'lucide-react',
  'Puzzle': 'lucide-react',
  'Shapes': 'lucide-react',
  // Art icons
  'Palette': 'lucide-react',
  'Paintbrush': 'lucide-react',
  'Brush': 'lucide-react',
  'Pen': 'lucide-react',
  'PenTool': 'lucide-react',
  'Pencil': 'lucide-react',
  'Eraser': 'lucide-react',
  'Highlighter': 'lucide-react',
  // Typography icons
  'Type': 'lucide-react',
  'Bold': 'lucide-react',
  'Italic': 'lucide-react',
  'Underline': 'lucide-react',
  'Strikethrough': 'lucide-react',
  'AlignLeft': 'lucide-react',
  'AlignCenter': 'lucide-react',
  'AlignRight': 'lucide-react',
  'AlignJustify': 'lucide-react',
  'Indent': 'lucide-react',
  'Outdent': 'lucide-react',
  'ListOrdered': 'lucide-react',
  'ListTodo': 'lucide-react',
  'ListChecks': 'lucide-react',
  'Quote': 'lucide-react',
  'Heading1': 'lucide-react',
  'Heading2': 'lucide-react',
  'Heading3': 'lucide-react',
  'Heading4': 'lucide-react',
  'Heading5': 'lucide-react',
  'Heading6': 'lucide-react',
  'Subscript': 'lucide-react',
  'Superscript': 'lucide-react',
  'Pilcrow': 'lucide-react',
  'TextCursor': 'lucide-react',
  'TextCursorInput': 'lucide-react',
  // Case icons
  'CaseSensitive': 'lucide-react',
  'CaseUpper': 'lucide-react',
  'CaseLower': 'lucide-react',
  'SpellCheck': 'lucide-react',
  'Languages': 'lucide-react',
  // Programming icons
  'Binary': 'lucide-react',
  'Regex': 'lucide-react',
  'Variable': 'lucide-react',
  // Math icons
  'Sigma': 'lucide-react',
  'Pi': 'lucide-react',
  'Infinity': 'lucide-react',
  'Percent': 'lucide-react',
  'Equal': 'lucide-react',
  'NotEqual': 'lucide-react',
  'LessThan': 'lucide-react',
  'GreaterThan': 'lucide-react',
  'LessThanOrEqual': 'lucide-react',
  'GreaterThanOrEqual': 'lucide-react',
  // Operation icons
  'PlusCircle': 'lucide-react',
  'MinusCircle': 'lucide-react',
  'Divide': 'lucide-react',
  'DivideCircle': 'lucide-react',
  'DivideSquare': 'lucide-react',
  'PlusSquare': 'lucide-react',
  'MinusSquare': 'lucide-react',
  'XSquare': 'lucide-react',
  'CheckSquare': 'lucide-react',
  'SquareCheck': 'lucide-react',
  'SquareX': 'lucide-react',
  // Box icons
  'Box': 'lucide-react',
  'BoxSelect': 'lucide-react',
  'Boxes': 'lucide-react',
  'Component': 'lucide-react',
  // Layer icons
  'Layers': 'lucide-react',
  'Layers2': 'lucide-react',
  'Layers3': 'lucide-react',
  'Stack': 'lucide-react',
  // Dashboard icons
  'LayoutDashboard': 'lucide-react',
  'LayoutGrid': 'lucide-react',
  'LayoutList': 'lucide-react',
  'LayoutTemplate': 'lucide-react',
  'Blocks': 'lucide-react',
  'Workflow': 'lucide-react',
  // Git icons
  'GitBranch': 'lucide-react',
  'GitCommit': 'lucide-react',
  'GitMerge': 'lucide-react',
  'GitPullRequest': 'lucide-react',
  'GitFork': 'lucide-react',
  // Social icons
  'Github': 'lucide-react',
  'Gitlab': 'lucide-react',
  'Slack': 'lucide-react',
  'Twitter': 'lucide-react',
  'Facebook': 'lucide-react',
  'Instagram': 'lucide-react',
  'Linkedin': 'lucide-react',
  'Youtube': 'lucide-react',
  'Twitch': 'lucide-react',
  'Discord': 'lucide-react',
  // Browser icons
  'Chrome': 'lucide-react',
  'Firefox': 'lucide-react',
  'Safari': 'lucide-react',
  'Edge': 'lucide-react',
  'Opera': 'lucide-react',
  // Design tool icons
  'Figma': 'lucide-react',
  'Framer': 'lucide-react',
  'Dribbble': 'lucide-react',
  'Codepen': 'lucide-react',
  'Codesandbox': 'lucide-react',
  // Transport icons
  'LifeBuoy': 'lucide-react',
  'Rocket': 'lucide-react',
  'Plane': 'lucide-react',
  'Car': 'lucide-react',
  'Bus': 'lucide-react',
  'Train': 'lucide-react',
  'Ship': 'lucide-react',
  'Anchor': 'lucide-react',
  'Bike': 'lucide-react',
  'Footprints': 'lucide-react',
};

// Common prop typos (case-insensitive key → correct value)
export const PROP_TYPOS: Record<string, string> = {
  'classname': 'className',
  'classNames': 'className',
  'class': 'className',
  'onclick': 'onClick',
  'onchange': 'onChange',
  'onsubmit': 'onSubmit',
  'oninput': 'onInput',
  'onkeydown': 'onKeyDown',
  'onkeyup': 'onKeyUp',
  'onkeypress': 'onKeyPress',
  'onfocus': 'onFocus',
  'onblur': 'onBlur',
  'onmouseover': 'onMouseOver',
  'onmouseout': 'onMouseOut',
  'onmouseenter': 'onMouseEnter',
  'onmouseleave': 'onMouseLeave',
  'onmousedown': 'onMouseDown',
  'onmouseup': 'onMouseUp',
  'ondrag': 'onDrag',
  'ondragstart': 'onDragStart',
  'ondragend': 'onDragEnd',
  'ondragenter': 'onDragEnter',
  'ondragleave': 'onDragLeave',
  'ondragover': 'onDragOver',
  'ondrop': 'onDrop',
  'onscroll': 'onScroll',
  'onload': 'onLoad',
  'onerror': 'onError',
  'ontouchstart': 'onTouchStart',
  'ontouchend': 'onTouchEnd',
  'ontouchmove': 'onTouchMove',
  'tabindex': 'tabIndex',
  'readonly': 'readOnly',
  'maxlength': 'maxLength',
  'minlength': 'minLength',
  'autocomplete': 'autoComplete',
  'autofocus': 'autoFocus',
  'autoplay': 'autoPlay',
  'htmlfor': 'htmlFor',
  'for': 'htmlFor',
  'srcset': 'srcSet',
  'crossorigin': 'crossOrigin',
  'colspan': 'colSpan',
  'rowspan': 'rowSpan',
  'cellpadding': 'cellPadding',
  'cellspacing': 'cellSpacing',
  'contenteditable': 'contentEditable',
  'spellcheck': 'spellCheck',
  'dangerouslysetinnerhtml': 'dangerouslySetInnerHTML',
  'defaultvalue': 'defaultValue',
  'defaultchecked': 'defaultChecked',
  'selectedindex': 'selectedIndex',
  'formaction': 'formAction',
  'formmethod': 'formMethod',
  'formtarget': 'formTarget',
  'formnovalidate': 'formNoValidate',
  'formenctype': 'formEncType',
  'acceptcharset': 'acceptCharset',
  'accesskey': 'accessKey',
  'usemap': 'useMap',
  'allowfullscreen': 'allowFullScreen',
  'frameborder': 'frameBorder',
  'marginheight': 'marginHeight',
  'marginwidth': 'marginWidth',
  'scrolling': 'scrolling',
  'srcdoc': 'srcDoc',
  'datetime': 'dateTime',
  'enctype': 'encType',
  'httpequiv': 'httpEquiv',
  'inputmode': 'inputMode',
  'enterkeyhint': 'enterKeyHint',
};

// Self-closing HTML tags that don't need closing tags in JSX
export const SELF_CLOSING_TAGS = new Set([
  'area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input',
  'link', 'meta', 'param', 'source', 'track', 'wbr'
]);

// Combined COMMON_IMPORTS for external use
export const COMMON_IMPORTS: Record<string, string> = {
  ...MOTION_IMPORTS,
  ...STATE_MANAGEMENT_IMPORTS,
  ...FORM_IMPORTS,
  ...ROUTING_IMPORTS,
  ...UI_LIBRARY_IMPORTS,
  ...TOAST_IMPORTS,
  ...CHART_IMPORTS,
  ...TABLE_IMPORTS,
  ...DND_IMPORTS,
  ...UTILITY_IMPORTS,
  ...LUCIDE_ICONS,
};

// All known imports combined (for comprehensive lookups)
export const ALL_KNOWN_IMPORTS: Record<string, string> = {
  ...REACT_IMPORTS,
  ...COMMON_IMPORTS,
};

// ============================================================================
// Known Lucide Icons for sandbox validation
// Used by sandboxHtml.ts to validate icon imports and replace unknown icons
// ============================================================================
export const KNOWN_LUCIDE_ICONS_LIST: string[] = [
  // Common UI icons
  'Activity', 'AlertCircle', 'AlertTriangle', 'Archive', 'ArrowDown', 'ArrowLeft', 'ArrowRight', 'ArrowUp',
  'Award', 'BarChart', 'BarChart2', 'Bell', 'Book', 'Bookmark', 'Box', 'Briefcase', 'Calendar', 'Camera',
  'Check', 'CheckCircle', 'ChevronDown', 'ChevronLeft', 'ChevronRight', 'ChevronUp', 'Circle', 'Clipboard',
  'Clock', 'Cloud', 'Code', 'Code2', 'Coffee', 'Cog', 'Command', 'Copy', 'CreditCard', 'Database', 'Delete',
  'Download', 'Edit', 'Edit2', 'Edit3', 'ExternalLink', 'Eye', 'EyeOff', 'Facebook', 'File', 'FileText',
  'Filter', 'Flag', 'Folder', 'FolderOpen', 'Gift', 'Github', 'Globe', 'Grid', 'Hash', 'Heart', 'HelpCircle',
  'Home', 'Image', 'Inbox', 'Info', 'Instagram', 'Key', 'Layers', 'Layout', 'LayoutDashboard', 'Link', 'Link2',
  'List', 'Loader', 'Loader2', 'Lock', 'LogIn', 'LogOut', 'Mail', 'Map', 'MapPin', 'Maximize', 'Maximize2',
  'Menu', 'MessageCircle', 'MessageSquare', 'Mic', 'Minimize', 'Minimize2', 'Minus', 'Monitor', 'Moon', 'MoreHorizontal',
  'MoreVertical', 'Move', 'Music', 'Navigation', 'Package', 'Paperclip', 'Pause', 'PenTool', 'Percent', 'Phone',
  'PieChart', 'Pin', 'Play', 'Plus', 'PlusCircle', 'Pocket', 'Power', 'Printer', 'Radio', 'RefreshCw', 'Repeat',
  'RotateCcw', 'RotateCw', 'Rss', 'Save', 'Search', 'Send', 'Server', 'Settings', 'Settings2', 'Share', 'Share2',
  'Shield', 'ShieldCheck', 'ShoppingBag', 'ShoppingCart', 'Shuffle', 'Sidebar', 'SkipBack', 'SkipForward', 'Slack',
  'Sliders', 'Smartphone', 'Smile', 'Sparkles', 'Speaker', 'Square', 'Star', 'Stop', 'Sun', 'Sunrise', 'Sunset',
  'Table', 'Tablet', 'Tag', 'Target', 'Terminal', 'ThumbsDown', 'ThumbsUp', 'ToggleLeft', 'ToggleRight', 'Tool',
  'Trash', 'Trash2', 'TrendingDown', 'TrendingUp', 'Triangle', 'Truck', 'Tv', 'Twitter', 'Type', 'Umbrella',
  'Underline', 'Unlock', 'Upload', 'UploadCloud', 'User', 'UserCheck', 'UserMinus', 'UserPlus', 'Users', 'UserX',
  'Video', 'VideoOff', 'Voicemail', 'Volume', 'Volume1', 'Volume2', 'VolumeX', 'Watch', 'Wifi', 'WifiOff', 'Wind',
  'X', 'XCircle', 'Youtube', 'Zap', 'ZapOff', 'ZoomIn', 'ZoomOut',
  // Additional common icons
  'Accessibility', 'AlignCenter', 'AlignJustify', 'AlignLeft', 'AlignRight', 'Anchor', 'Aperture', 'App',
  'Apple', 'ArrowBigDown', 'ArrowBigLeft', 'ArrowBigRight', 'ArrowBigUp', 'ArrowDownCircle', 'ArrowLeftCircle',
  'ArrowRightCircle', 'ArrowUpCircle', 'AtSign', 'Axe', 'Baby', 'Backpack', 'Badge', 'BadgeCheck', 'BadgeDollarSign',
  'BadgeInfo', 'BadgeMinus', 'BadgePlus', 'Banknote', 'Battery', 'BatteryCharging', 'BatteryFull', 'BatteryLow',
  'BatteryMedium', 'Beaker', 'Bean', 'Bed', 'Beer', 'BellMinus', 'BellOff', 'BellPlus', 'BellRing', 'Bike',
  'Binary', 'Bird', 'Bitcoin', 'Blend', 'Blocks', 'Bluetooth', 'Bold', 'Bomb', 'Bone', 'BookCopy', 'BookDashed',
  'Bot', 'Boxes', 'Brain', 'BrainCircuit', 'Brush', 'Bug', 'Building', 'Building2', 'Bus', 'Cable', 'Cake',
  'Calculator', 'CalendarCheck', 'CalendarClock', 'CalendarDays', 'CalendarHeart', 'CalendarMinus', 'CalendarOff',
  'CalendarPlus', 'CalendarRange', 'CalendarSearch', 'CalendarX', 'CameraOff', 'Candy', 'Car', 'Carrot', 'Cat',
  'Cigarette', 'CircleDashed', 'CircleDot', 'CircleOff', 'CircleSlash', 'Citrus', 'Clapperboard', 'ClipboardCheck',
  'ClipboardCopy', 'ClipboardEdit', 'ClipboardList', 'ClipboardSignature', 'ClipboardType', 'ClipboardX',
  'CloudCog', 'CloudDownload', 'CloudDrizzle', 'CloudFog', 'CloudHail', 'CloudLightning', 'CloudMoon', 'CloudMoonRain',
  'CloudOff', 'CloudRain', 'CloudRainWind', 'CloudSnow', 'CloudSun', 'CloudSunRain', 'CloudUpload', 'Clover', 'Club',
  'Coins', 'Columns', 'Combine', 'Compass', 'Component', 'Computer', 'ConciergeBell', 'Cone', 'Construction', 'Contact',
  'Container', 'Contrast', 'Cookie', 'CopyCheck', 'CopyMinus', 'CopyPlus', 'CopySlash', 'CopyX', 'Copyright',
  'CornerDownLeft', 'CornerDownRight', 'CornerLeftDown', 'CornerLeftUp', 'CornerRightDown', 'CornerRightUp',
  'CornerUpLeft', 'CornerUpRight', 'Cpu', 'Croissant', 'Crop', 'Cross', 'Crosshair', 'Crown', 'Cup', 'Currency',
  'DatabaseBackup', 'Diamond', 'Dice1', 'Dice2', 'Dice3', 'Dice4', 'Dice5', 'Dice6', 'Dices', 'Diff', 'Disc',
  'Disc2', 'Divide', 'DivideCircle', 'DivideSquare', 'Dna', 'DnaOff', 'Dog', 'DollarSign', 'Donut', 'DoorClosed',
  'DoorOpen', 'Dot', 'DownloadCloud', 'Dribbble', 'Droplet', 'Droplets', 'Drum', 'Drumstick', 'Dumbbell', 'Ear',
  'EarOff', 'Eclipse', 'Egg', 'EggFried', 'EggOff', 'Equal', 'EqualNot', 'Eraser', 'Euro', 'Expand', 'Factory',
  'Fan', 'FastForward', 'Feather', 'Fence', 'FerrisWheel', 'Figma', 'FileArchive', 'FileAudio', 'FileAxis3d',
  'FileBadge', 'FileBadge2', 'FileBarChart', 'FileBarChart2', 'FileBox', 'FileCheck', 'FileCheck2', 'FileClock',
  'FileCode', 'FileCode2', 'FileCog', 'FileDiff', 'FileDigit', 'FileDown', 'FileEdit', 'FileHeart', 'FileImage',
  'FileInput', 'FileJson', 'FileJson2', 'FileKey', 'FileKey2', 'FileLineChart', 'FileLock', 'FileLock2',
  'FileMinus', 'FileMinus2', 'FileMusic', 'FileOutput', 'FilePieChart', 'FilePlus', 'FilePlus2', 'FileQuestion',
  'FileScan', 'FileSearch', 'FileSearch2', 'FileSliders', 'FileSpreadsheet', 'FileStack', 'FileSymlink',
  'FileTerminal', 'FileType', 'FileType2', 'FileUp', 'FileVideo', 'FileVideo2', 'FileVolume', 'FileVolume2',
  'FileWarning', 'FileX', 'FileX2', 'Files', 'Film', 'Fingerprint', 'Fish', 'FishOff', 'FishSymbol', 'Flame',
  'FlameKindling', 'Flashlight', 'FlashlightOff', 'Flask', 'FlaskConical', 'FlaskRound', 'FlipHorizontal',
  'FlipHorizontal2', 'FlipVertical', 'FlipVertical2', 'Flower', 'Flower2', 'Focus', 'FolderArchive', 'FolderCheck',
  'FolderClock', 'FolderClosed', 'FolderCog', 'FolderDot', 'FolderDown', 'FolderEdit', 'FolderGit', 'FolderGit2',
  'FolderHeart', 'FolderInput', 'FolderKanban', 'FolderKey', 'FolderLock', 'FolderMinus', 'FolderOutput',
  'FolderPlus', 'FolderRoot', 'FolderSearch', 'FolderSearch2', 'FolderSymlink', 'FolderSync', 'FolderTree',
  'FolderUp', 'FolderX', 'Folders', 'Footprints', 'Forklift', 'FormInput', 'Forward', 'Frame', 'Framer', 'Frown',
  'Fuel', 'Fullscreen', 'FunctionSquare', 'GalleryHorizontal', 'GalleryHorizontalEnd', 'GalleryThumbnails',
  'GalleryVertical', 'GalleryVerticalEnd', 'Gamepad', 'Gamepad2', 'Gauge', 'Gavel', 'Gem', 'Ghost', 'GiftCard',
  'GitBranch', 'GitBranchPlus', 'GitCommit', 'GitCompare', 'GitFork', 'GitMerge', 'GitPullRequest',
  'GitPullRequestClosed', 'GitPullRequestDraft', 'Glasses', 'Globe2', 'Goal', 'Grab', 'GraduationCap', 'Grape',
  'Grid2X2', 'Grid3X3', 'Grip', 'GripHorizontal', 'GripVertical', 'Group', 'Hammer', 'Hand', 'HandMetal',
  'HardDrive', 'HardDriveDownload', 'HardDriveUpload', 'HardHat', 'Haze', 'HdmiPort', 'Heading', 'Heading1',
  'Heading2', 'Heading3', 'Heading4', 'Heading5', 'Heading6', 'Headphones', 'HeartCrack', 'HeartHandshake',
  'HeartOff', 'HeartPulse', 'Heater', 'Hexagon', 'Highlighter', 'History', 'Hop', 'HopOff', 'Hotel', 'Hourglass',
  'IceCream', 'IceCream2', 'ImageDown', 'ImageMinus', 'ImageOff', 'ImagePlus', 'Import', 'Indent', 'IndianRupee',
  'Infinity', 'Inspect', 'Italic', 'JapaneseYen', 'Joystick', 'Kanban', 'KanbanSquare', 'KanbanSquareDashed',
  'KeyRound', 'KeySquare', 'Keyboard', 'Lamp', 'LampCeiling', 'LampDesk', 'LampFloor', 'LampWallDown', 'LampWallUp',
  'LandPlot', 'Landmark', 'Languages', 'Laptop', 'Laptop2', 'Lasso', 'LassoSelect', 'Laugh', 'LayoutGrid',
  'LayoutList', 'LayoutPanelLeft', 'LayoutPanelTop', 'LayoutTemplate', 'Leaf', 'LeafyGreen', 'Library', 'LifeBuoy',
  'Ligature', 'Lightbulb', 'LightbulbOff', 'LineChart', 'ListCheck', 'ListChecks', 'ListCollapse', 'ListEnd',
  'ListFilter', 'ListMinus', 'ListMusic', 'ListOrdered', 'ListPlus', 'ListRestart', 'ListStart', 'ListTodo',
  'ListTree', 'ListVideo', 'ListX', 'Locate', 'LocateFixed', 'LocateOff', 'LockKeyhole', 'LockKeyholeOpen',
  'LockOpen', 'Lollipop', 'Luggage', 'Magnet', 'MailCheck', 'MailMinus', 'MailOpen', 'MailPlus', 'MailQuestion',
  'MailSearch', 'MailWarning', 'MailX', 'Mailbox', 'Mails', 'MapPinOff', 'Martini', 'Megaphone', 'MegaphoneOff',
  'Meh', 'MemoryStick', 'MenuSquare', 'Merge', 'MessageCircleCode', 'MessageSquareCode', 'MessageSquareDashed',
  'MessageSquareDot', 'MessageSquareHeart', 'MessageSquareMore', 'MessageSquareOff', 'MessageSquarePlus',
  'MessageSquareQuote', 'MessageSquareReply', 'MessageSquareShare', 'MessageSquareText', 'MessageSquareWarning',
  'MessageSquareX', 'MessagesSquare', 'MicOff', 'Microchip', 'Microscope', 'Microwave', 'Milestone', 'Milk',
  'MilkOff', 'MinusCircle', 'MinusSquare', 'MonitorCheck', 'MonitorDot', 'MonitorDown', 'MonitorOff', 'MonitorPause',
  'MonitorPlay', 'MonitorSmartphone', 'MonitorSpeaker', 'MonitorStop', 'MonitorUp', 'MonitorX', 'MoonStar',
  'Mountain', 'MountainSnow', 'Mouse', 'MousePointer', 'MousePointer2', 'MousePointerClick', 'MoveDown',
  'MoveDownLeft', 'MoveDownRight', 'MoveDiagonal', 'MoveDiagonal2', 'MoveHorizontal', 'MoveLeft', 'MoveRight',
  'MoveUp', 'MoveUpLeft', 'MoveUpRight', 'MoveVertical', 'Music2', 'Music3', 'Music4', 'Navigation2', 'NavigationOff',
  'Network', 'Newspaper', 'Nfc', 'Notebook', 'NotebookPen', 'NotebookTabs', 'NotebookText', 'NotepadText',
  'NotepadTextDashed', 'Nut', 'NutOff', 'Octagon', 'Option', 'Orbit', 'Outdent', 'PackageCheck', 'PackageMinus',
  'PackageOpen', 'PackagePlus', 'PackageSearch', 'PackageX', 'PaintBucket', 'Paintbrush', 'Paintbrush2', 'Palette',
  'PalmTree', 'PanelBottom', 'PanelBottomClose', 'PanelBottomDashed', 'PanelBottomOpen', 'PanelLeft', 'PanelLeftClose',
  'PanelLeftDashed', 'PanelLeftOpen', 'PanelRight', 'PanelRightClose', 'PanelRightDashed', 'PanelRightOpen',
  'PanelTop', 'PanelTopClose', 'PanelTopDashed', 'PanelTopOpen', 'Parentheses', 'ParkingCircle', 'ParkingCircleOff',
  'ParkingMeter', 'ParkingSquare', 'ParkingSquareOff', 'PartyPopper', 'PauseCircle', 'PauseOctagon', 'PawPrint',
  'PcCase', 'Pen', 'PenLine', 'Pencil', 'PencilLine', 'Pentagon', 'PercentCircle', 'PercentDiamond', 'PercentSquare',
  'PersonStanding', 'PhoneCall', 'PhoneForwarded', 'PhoneIncoming', 'PhoneMissed', 'PhoneOff', 'PhoneOutgoing',
  'Pi', 'Piano', 'Pickaxe', 'PictureInPicture', 'PictureInPicture2', 'PiggyBank', 'Pilcrow', 'PilcrowSquare',
  'Pill', 'PinOff', 'Pipette', 'Pizza', 'Plane', 'PlaneLanding', 'PlaneTakeoff', 'PlayCircle', 'PlaySquare',
  'Plug', 'Plug2', 'PlugZap', 'PlugZap2', 'PlusSquare', 'Podcast', 'Pointer', 'PointerOff', 'Popcorn', 'Popsicle',
  'PoundSterling', 'PowerOff', 'Presentation', 'PrinterCheck', 'Projector', 'Proportions', 'Puzzle', 'Pyramid',
  'QrCode', 'Quote', 'Rabbit', 'Radar', 'Radiation', 'RadioReceiver', 'RadioTower', 'Rainbow', 'Rat', 'Ratio',
  'Receipt', 'ReceiptCent', 'ReceiptEuro', 'ReceiptIndianRupee', 'ReceiptJapaneseYen', 'ReceiptPoundSterling',
  'ReceiptRussianRuble', 'ReceiptSwissFranc', 'ReceiptText', 'RectangleHorizontal', 'RectangleVertical', 'Recycle',
  'Redo', 'Redo2', 'RefreshCcw', 'RefreshCcwDot', 'RefreshCwOff', 'Refrigerator', 'Regex', 'RemoveFormatting',
  'Repeat1', 'Repeat2', 'Replace', 'ReplaceAll', 'Reply', 'ReplyAll', 'Rewind', 'Ribbon', 'Rocket', 'RockingChair',
  'RollerCoaster', 'Rotate3d', 'Route', 'RouteOff', 'Router', 'Rows', 'Ruler', 'RussianRuble', 'Sailboat', 'Salad',
  'Sandwich', 'Satellite', 'SatelliteDish', 'Scale', 'Scale3d', 'Scaling', 'Scan', 'ScanBarcode', 'ScanEye',
  'ScanFace', 'ScanLine', 'ScanSearch', 'ScanText', 'School', 'School2', 'Scissors', 'ScissorsLineDashed',
  'ScreenShare', 'ScreenShareOff', 'Scroll', 'ScrollText', 'SearchCheck', 'SearchCode', 'SearchSlash', 'SearchX',
  'Section', 'SendHorizontal', 'SendToBack', 'SeparatorHorizontal', 'SeparatorVertical', 'ServerCog', 'ServerCrash',
  'ServerOff', 'Shapes', 'ShieldAlert', 'ShieldBan', 'ShieldClose', 'ShieldEllipsis', 'ShieldHalf', 'ShieldMinus',
  'ShieldOff', 'ShieldPlus', 'ShieldQuestion', 'ShieldX', 'Ship', 'ShipWheel', 'Shirt', 'ShoppingBasket', 'Shovel',
  'ShowerHead', 'Shrink', 'Shrub', 'SidebarClose', 'SidebarOpen', 'Sigma', 'Signal', 'SignalHigh', 'SignalLow',
  'SignalMedium', 'SignalZero', 'Signpost', 'SignpostBig', 'Siren', 'SlidersHorizontal', 'SmilePlus', 'Snail',
  'Snowflake', 'Sofa', 'Soup', 'Space', 'Spade', 'Sparkle', 'Speech', 'SpellCheck', 'SpellCheck2', 'Spline',
  'Split', 'SprayCan', 'Sprout', 'SquareAsterisk', 'SquareCode', 'SquareDashedBottom', 'SquareDashedBottomCode',
  'SquareDot', 'SquareEqual', 'SquareGantt', 'SquareKanban', 'SquareLibrary', 'SquareM', 'SquareMenu', 'SquareMinus',
  'SquareParking', 'SquareParkingOff', 'SquarePen', 'SquarePercent', 'SquarePi', 'SquarePlay', 'SquarePlus',
  'SquarePower', 'SquareRadical', 'SquareScissors', 'SquareSigma', 'SquareSlash', 'SquareSplitHorizontal',
  'SquareSplitVertical', 'SquareStack', 'SquareTerminal', 'SquareUser', 'SquareUserRound', 'SquareX', 'Squircle',
  'Squirrel', 'Stamp', 'StarHalf', 'StarOff', 'Stars', 'StepBack', 'StepForward', 'Stethoscope', 'Sticker',
  'StickyNote', 'Stopwatch', 'Store', 'StretchHorizontal', 'StretchVertical', 'Strikethrough', 'Subscript',
  'Subtitles', 'SunDim', 'SunMedium', 'SunMoon', 'SunSnow', 'Sunglasses', 'Superscript', 'SwatchBook', 'SwissFranc',
  'SwitchCamera', 'Sword', 'Swords', 'Syringe', 'Table2', 'TableCellsMerge', 'TableCellsSplit', 'TableProperties',
  'Tablets', 'Tally1', 'Tally2', 'Tally3', 'Tally4', 'Tally5', 'Tangent', 'Tape', 'TargetOff', 'Telescope', 'Tent',
  'TentTree', 'TerminalSquare', 'TestTube', 'TestTube2', 'TestTubes', 'Text', 'TextCursor', 'TextCursorInput',
  'TextQuote', 'TextSearch', 'TextSelect', 'Theater', 'Thermometer', 'ThermometerSnowflake', 'ThermometerSun',
  'TicketCheck', 'TicketMinus', 'TicketPercent', 'TicketPlus', 'TicketSlash', 'TicketX', 'Tickets', 'TicketsPlane',
  'Timer', 'TimerOff', 'TimerReset', 'Tornado', 'Torus', 'Touchpad', 'TouchpadOff', 'TowerControl', 'ToyBrick',
  'Tractor', 'TrafficCone', 'Train', 'TrainFront', 'TrainFrontTunnel', 'TrainTrack', 'TramFront', 'TreeDeciduous',
  'TreePalm', 'TreePine', 'Trees', 'Trello', 'TriangleAlert', 'TriangleRight', 'Trophy', 'Turtle', 'TvMinimal',
  'TvMinimalPlay', 'Twitch', 'TypeOutline', 'UmbrellaOff', 'Undo', 'Undo2', 'UndoDot', 'UnfoldHorizontal',
  'UnfoldVertical', 'Ungroup', 'University', 'Unlink', 'Unlink2', 'Unplug', 'Usb', 'UserCircle', 'UserCircle2',
  'UserCog', 'UserRound', 'UserRoundCheck', 'UserRoundCog', 'UserRoundMinus', 'UserRoundPlus', 'UserRoundSearch',
  'UserRoundX', 'UserSearch', 'UserSquare', 'UserSquare2', 'UsersRound', 'Utensils', 'UtensilsCrossed', 'UtilityPole',
  'Variable', 'Vault', 'Vegan', 'VenetianMask', 'Vibrate', 'VibrateOff', 'Videotape', 'View', 'Wallet', 'Wallet2',
  'WalletCards', 'WalletMinimal', 'Wallpaper', 'Wand', 'Wand2', 'Warehouse', 'WashingMachine', 'Waves', 'Waypoints',
  'Webcam', 'Webhook', 'Weight', 'Wheat', 'WheatOff', 'WholeWord', 'WineOff', 'Workflow', 'Worm', 'WrapText',
  'XOctagon', 'XSquare',
];
