/**
 * Prompts Index
 *
 * Barrel export for AI prompt templates and system instructions.
 */

export {
  buildInspectEditInstruction,
  CONSULTANT_SYSTEM_INSTRUCTION,
  BASE_GENERATION_INSTRUCTION,
  SEARCH_REPLACE_MODE_INSTRUCTION,
  STANDARD_UPDATE_INSTRUCTION,
  STANDARD_UPDATE_INSTRUCTION_MARKER,
  CONTINUATION_SYSTEM_INSTRUCTION,
  CONTINUATION_SYSTEM_INSTRUCTION_MARKER,
  PROMPT_ENGINEER_SYSTEM,
  PROMPT_ENGINEER_STEP1,
  PROMPT_ENGINEER_STEP2,
  PROMPT_ENGINEER_STEP3,
  PROMPT_ENGINEER_FINAL,
  ERROR_FIX_SYSTEM_PROMPT,
} from './systemInstructions';
