import React, { useState, useEffect, useMemo } from 'react';
import {
  Key, Plus, Trash2, Eye, EyeOff, Copy, Check, Shield,
  AlertTriangle, Info, Lock, Unlock, RefreshCw, Sparkles,
  Database, Cloud, CreditCard, Mail, Globe, Server
} from 'lucide-react';
import { FileSystem } from '../../types';

interface EnvironmentPanelProps {
  files: FileSystem;
  setFiles: (files: FileSystem) => void;
}

interface EnvVariable {
  key: string;
  value: string;
  isSecret: boolean;
  category?: string;
}

// Common environment variable templates
const ENV_TEMPLATES: Record<string, { key: string; placeholder: string; category: string; icon: React.ReactNode }[]> = {
  'API Keys': [
    { key: 'API_KEY', placeholder: 'your-api-key', category: 'api', icon: <Key className="w-3 h-3" /> },
    { key: 'OPENAI_API_KEY', placeholder: 'sk-...', category: 'api', icon: <Sparkles className="w-3 h-3" /> },
    { key: 'STRIPE_SECRET_KEY', placeholder: 'sk_live_...', category: 'api', icon: <CreditCard className="w-3 h-3" /> },
    { key: 'STRIPE_PUBLISHABLE_KEY', placeholder: 'pk_live_...', category: 'api', icon: <CreditCard className="w-3 h-3" /> },
  ],
  'Database': [
    { key: 'DATABASE_URL', placeholder: 'postgresql://user:pass@host:5432/db', category: 'db', icon: <Database className="w-3 h-3" /> },
    { key: 'REDIS_URL', placeholder: 'redis://localhost:6379', category: 'db', icon: <Database className="w-3 h-3" /> },
    { key: 'MONGODB_URI', placeholder: 'mongodb://localhost:27017/db', category: 'db', icon: <Database className="w-3 h-3" /> },
  ],
  'Auth': [
    { key: 'JWT_SECRET', placeholder: 'your-jwt-secret', category: 'auth', icon: <Lock className="w-3 h-3" /> },
    { key: 'SESSION_SECRET', placeholder: 'your-session-secret', category: 'auth', icon: <Shield className="w-3 h-3" /> },
    { key: 'NEXTAUTH_SECRET', placeholder: 'your-nextauth-secret', category: 'auth', icon: <Shield className="w-3 h-3" /> },
    { key: 'NEXTAUTH_URL', placeholder: 'http://localhost:3000', category: 'auth', icon: <Globe className="w-3 h-3" /> },
  ],
  'Services': [
    { key: 'SMTP_HOST', placeholder: 'smtp.example.com', category: 'service', icon: <Mail className="w-3 h-3" /> },
    { key: 'SMTP_USER', placeholder: 'user@example.com', category: 'service', icon: <Mail className="w-3 h-3" /> },
    { key: 'SMTP_PASS', placeholder: 'password', category: 'service', icon: <Mail className="w-3 h-3" /> },
    { key: 'AWS_ACCESS_KEY_ID', placeholder: 'AKIA...', category: 'service', icon: <Cloud className="w-3 h-3" /> },
    { key: 'AWS_SECRET_ACCESS_KEY', placeholder: 'secret', category: 'service', icon: <Cloud className="w-3 h-3" /> },
  ],
  'App Config': [
    { key: 'NODE_ENV', placeholder: 'development', category: 'config', icon: <Server className="w-3 h-3" /> },
    { key: 'PORT', placeholder: '3000', category: 'config', icon: <Server className="w-3 h-3" /> },
    { key: 'APP_URL', placeholder: 'http://localhost:3000', category: 'config', icon: <Globe className="w-3 h-3" /> },
  ],
};

// Parse .env content to variables
function parseEnvFile(content: string): EnvVariable[] {
  const variables: EnvVariable[] = [];
  const lines = content.split('\n');

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const match = trimmed.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/i);
    if (match) {
      const [, key, rawValue] = match;
      // Remove quotes if present
      let value = rawValue;
      if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
        value = value.slice(1, -1);
      }

      // Determine if it's a secret based on key name
      const isSecret = /secret|password|key|token|auth/i.test(key);

      variables.push({ key, value, isSecret });
    }
  }

  return variables;
}

// Generate .env content from variables
function generateEnvFile(variables: EnvVariable[]): string {
  let content = '# Environment Variables\n';
  content += '# Generated by FluidFlow\n';
  content += `# Last updated: ${new Date().toISOString()}\n\n`;

  for (const v of variables) {
    // Quote values with spaces or special characters
    const needsQuotes = /[\s#=]/.test(v.value);
    const value = needsQuotes ? `"${v.value}"` : v.value;
    content += `${v.key}=${value}\n`;
  }

  return content;
}

// Generate .gitignore content
function generateGitignore(existing: string = ''): string {
  const requiredEntries = [
    '# Dependencies',
    'node_modules/',
    '',
    '# Environment',
    '.env',
    '.env.local',
    '.env.*.local',
    '',
    '# Build',
    'dist/',
    'build/',
    '.next/',
    '',
    '# IDE',
    '.idea/',
    '.vscode/',
    '*.swp',
    '*.swo',
    '',
    '# OS',
    '.DS_Store',
    'Thumbs.db',
    '',
    '# Logs',
    '*.log',
    'npm-debug.log*',
  ];

  // Parse existing entries
  const existingLines = existing.split('\n').map(l => l.trim());
  const existingSet = new Set(existingLines.filter(l => l && !l.startsWith('#')));

  // Merge with required
  const result: string[] = [];
  for (const entry of requiredEntries) {
    if (entry.startsWith('#') || entry === '') {
      result.push(entry);
    } else if (!existingSet.has(entry)) {
      result.push(entry);
      existingSet.add(entry);
    } else {
      result.push(entry);
    }
  }

  // Add any extra entries from existing
  for (const line of existingLines) {
    if (line && !line.startsWith('#') && !result.includes(line)) {
      result.push(line);
    }
  }

  return result.join('\n');
}

export const EnvironmentPanel: React.FC<EnvironmentPanelProps> = ({ files, setFiles }) => {
  const [variables, setVariables] = useState<EnvVariable[]>([]);
  const [showValues, setShowValues] = useState<Record<string, boolean>>({});
  const [copied, setCopied] = useState<string | null>(null);
  const [hasChanges, setHasChanges] = useState(false);
  const [showTemplates, setShowTemplates] = useState(false);
  const [newKey, setNewKey] = useState('');
  const [newValue, setNewValue] = useState('');

  // Load .env file on mount
  useEffect(() => {
    const envFile = files['.env'] || files['.env.local'];
    if (envFile) {
      setVariables(parseEnvFile(envFile));
    }
  }, []);

  // Check if .gitignore exists and has .env
  const gitignoreStatus = useMemo(() => {
    const gitignore = files['.gitignore'] || '';
    const hasEnv = gitignore.includes('.env');
    return { exists: !!files['.gitignore'], hasEnv };
  }, [files]);

  const addVariable = (key: string = newKey, value: string = newValue) => {
    if (!key.trim()) return;

    const isSecret = /secret|password|key|token|auth/i.test(key);
    setVariables(prev => [...prev.filter(v => v.key !== key), { key: key.toUpperCase(), value, isSecret }]);
    setNewKey('');
    setNewValue('');
    setHasChanges(true);
  };

  const updateVariable = (index: number, updates: Partial<EnvVariable>) => {
    setVariables(prev => prev.map((v, i) => i === index ? { ...v, ...updates } : v));
    setHasChanges(true);
  };

  const deleteVariable = (index: number) => {
    setVariables(prev => prev.filter((_, i) => i !== index));
    setHasChanges(true);
  };

  const toggleShowValue = (key: string) => {
    setShowValues(prev => ({ ...prev, [key]: !prev[key] }));
  };

  const copyValue = async (value: string, key: string) => {
    await navigator.clipboard.writeText(value);
    setCopied(key);
    setTimeout(() => setCopied(null), 2000);
  };

  const saveEnvFile = () => {
    const envContent = generateEnvFile(variables);
    const newFiles = { ...files, '.env': envContent };

    // Also ensure .gitignore exists and has .env
    if (!gitignoreStatus.hasEnv) {
      newFiles['.gitignore'] = generateGitignore(files['.gitignore'] || '');
    }

    setFiles(newFiles);
    setHasChanges(false);
  };

  const generateExampleEnv = () => {
    let content = '# Example Environment Variables\n';
    content += '# Copy this to .env and fill in your values\n\n';

    for (const v of variables) {
      content += `${v.key}=your_${v.key.toLowerCase()}_here\n`;
    }

    setFiles({ ...files, '.env.example': content });
  };

  const addFromTemplate = (key: string, placeholder: string) => {
    addVariable(key, '');
    setShowTemplates(false);
  };

  return (
    <div className="flex flex-col h-full w-full bg-[#0d1117] overflow-hidden">
      {/* Header */}
      <div className="flex-none flex items-center justify-between px-4 py-3 bg-[#0a0e16] border-b border-white/5">
        <div className="flex items-center gap-3">
          <div className="p-1.5 bg-amber-500/20 rounded-lg">
            <Shield className="w-4 h-4 text-amber-400" />
          </div>
          <div>
            <h2 className="text-sm font-semibold text-white">Environment Variables</h2>
            <p className="text-[10px] text-slate-500">{variables.length} variables configured</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          {hasChanges && (
            <span className="text-[10px] px-2 py-0.5 bg-amber-500/20 text-amber-400 rounded animate-pulse">
              unsaved
            </span>
          )}
          <button
            onClick={() => setShowTemplates(!showTemplates)}
            className={`p-2 rounded-lg transition-colors ${
              showTemplates ? 'bg-purple-500/20 text-purple-400' : 'bg-white/5 text-slate-400 hover:text-white'
            }`}
            title="Add from templates"
          >
            <Sparkles className="w-4 h-4" />
          </button>
          <button
            onClick={generateExampleEnv}
            className="p-2 bg-white/5 text-slate-400 hover:text-white rounded-lg transition-colors"
            title="Generate .env.example"
          >
            <RefreshCw className="w-4 h-4" />
          </button>
          <button
            onClick={saveEnvFile}
            disabled={!hasChanges}
            className={`flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium rounded-lg transition-colors ${
              hasChanges
                ? 'bg-emerald-600 hover:bg-emerald-500 text-white'
                : 'bg-white/5 text-slate-500'
            }`}
          >
            <Key className="w-3.5 h-3.5" />
            Save
          </button>
        </div>
      </div>

      {/* Security Warning */}
      {!gitignoreStatus.hasEnv && variables.length > 0 && (
        <div className="flex-none px-4 py-2 bg-red-500/10 border-b border-red-500/20">
          <div className="flex items-center gap-2 text-red-400">
            <AlertTriangle className="w-4 h-4 flex-shrink-0" />
            <span className="text-xs">
              <strong>.env is not in .gitignore!</strong> Your secrets may be exposed. Save to auto-fix.
            </span>
          </div>
        </div>
      )}

      {/* Templates Panel */}
      {showTemplates && (
        <div className="flex-none px-4 py-3 bg-purple-500/5 border-b border-purple-500/20 max-h-64 overflow-y-auto">
          <div className="space-y-3">
            {Object.entries(ENV_TEMPLATES).map(([category, templates]) => (
              <div key={category}>
                <h4 className="text-[10px] text-slate-500 uppercase tracking-wide mb-1.5">{category}</h4>
                <div className="flex flex-wrap gap-1.5">
                  {templates.map(t => (
                    <button
                      key={t.key}
                      onClick={() => addFromTemplate(t.key, t.placeholder)}
                      disabled={variables.some(v => v.key === t.key)}
                      className="flex items-center gap-1.5 px-2 py-1 text-[11px] bg-slate-800 hover:bg-slate-700 disabled:opacity-50 disabled:cursor-not-allowed text-slate-300 rounded transition-colors"
                    >
                      {t.icon}
                      {t.key}
                    </button>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Add New Variable */}
      <div className="flex-none px-4 py-3 bg-slate-800/30 border-b border-white/5">
        <div className="flex items-center gap-2">
          <input
            value={newKey}
            onChange={(e) => setNewKey(e.target.value.toUpperCase().replace(/[^A-Z0-9_]/g, ''))}
            placeholder="VARIABLE_NAME"
            className="flex-1 px-3 py-2 bg-slate-800 border border-white/10 rounded-lg text-sm text-white placeholder-slate-500 outline-none focus:border-blue-500/50 font-mono"
            onKeyDown={(e) => e.key === 'Enter' && addVariable()}
          />
          <input
            value={newValue}
            onChange={(e) => setNewValue(e.target.value)}
            placeholder="value"
            className="flex-1 px-3 py-2 bg-slate-800 border border-white/10 rounded-lg text-sm text-white placeholder-slate-500 outline-none focus:border-blue-500/50"
            onKeyDown={(e) => e.key === 'Enter' && addVariable()}
          />
          <button
            onClick={() => addVariable()}
            disabled={!newKey.trim()}
            className="p-2 bg-emerald-600 hover:bg-emerald-500 disabled:bg-slate-700 text-white rounded-lg transition-colors"
          >
            <Plus className="w-4 h-4" />
          </button>
        </div>
      </div>

      {/* Variables List */}
      <div className="flex-1 min-h-0 overflow-y-auto custom-scrollbar">
        {variables.length === 0 ? (
          <div className="h-full flex flex-col items-center justify-center text-slate-500 p-8">
            <Shield className="w-12 h-12 mb-4 opacity-30" />
            <h3 className="text-sm font-medium text-slate-400 mb-2">No environment variables</h3>
            <p className="text-xs text-center mb-4">
              Add variables above or use templates to get started
            </p>
            <button
              onClick={() => setShowTemplates(true)}
              className="flex items-center gap-2 px-4 py-2 bg-purple-600 hover:bg-purple-500 text-white text-sm rounded-lg transition-colors"
            >
              <Sparkles className="w-4 h-4" />
              Browse Templates
            </button>
          </div>
        ) : (
          <div className="divide-y divide-white/5">
            {variables.map((variable, index) => (
              <div key={variable.key} className="px-4 py-3 hover:bg-white/[0.02] group">
                <div className="flex items-center gap-3">
                  <div className="flex-shrink-0">
                    {variable.isSecret ? (
                      <Lock className="w-4 h-4 text-amber-400" />
                    ) : (
                      <Unlock className="w-4 h-4 text-slate-500" />
                    )}
                  </div>

                  <div className="flex-1 min-w-0">
                    <input
                      value={variable.key}
                      onChange={(e) => updateVariable(index, { key: e.target.value.toUpperCase().replace(/[^A-Z0-9_]/g, '') })}
                      className="w-full bg-transparent text-sm font-mono text-emerald-400 outline-none"
                    />
                  </div>

                  <div className="flex-1 min-w-0">
                    <div className="relative">
                      <input
                        type={variable.isSecret && !showValues[variable.key] ? 'password' : 'text'}
                        value={variable.value}
                        onChange={(e) => updateVariable(index, { value: e.target.value })}
                        className="w-full bg-slate-800/50 border border-white/5 rounded px-2 py-1 text-sm text-slate-300 outline-none focus:border-blue-500/50"
                        placeholder="(empty)"
                      />
                    </div>
                  </div>

                  <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                    {variable.isSecret && (
                      <button
                        onClick={() => toggleShowValue(variable.key)}
                        className="p-1.5 hover:bg-white/10 rounded transition-colors"
                        title={showValues[variable.key] ? 'Hide value' : 'Show value'}
                      >
                        {showValues[variable.key] ? (
                          <EyeOff className="w-3.5 h-3.5 text-slate-400" />
                        ) : (
                          <Eye className="w-3.5 h-3.5 text-slate-400" />
                        )}
                      </button>
                    )}
                    <button
                      onClick={() => copyValue(variable.value, variable.key)}
                      className="p-1.5 hover:bg-white/10 rounded transition-colors"
                      title="Copy value"
                    >
                      {copied === variable.key ? (
                        <Check className="w-3.5 h-3.5 text-green-400" />
                      ) : (
                        <Copy className="w-3.5 h-3.5 text-slate-400" />
                      )}
                    </button>
                    <button
                      onClick={() => deleteVariable(index)}
                      className="p-1.5 hover:bg-red-500/20 rounded transition-colors"
                      title="Delete"
                    >
                      <Trash2 className="w-3.5 h-3.5 text-red-400" />
                    </button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Footer Info */}
      <div className="flex-none px-4 py-2 bg-slate-800/30 border-t border-white/5">
        <div className="flex items-center justify-between text-[10px] text-slate-500">
          <div className="flex items-center gap-4">
            <span className="flex items-center gap-1">
              <Lock className="w-3 h-3" />
              {variables.filter(v => v.isSecret).length} secrets
            </span>
            <span className="flex items-center gap-1">
              {gitignoreStatus.hasEnv ? (
                <Check className="w-3 h-3 text-green-400" />
              ) : (
                <AlertTriangle className="w-3 h-3 text-red-400" />
              )}
              .gitignore {gitignoreStatus.hasEnv ? 'configured' : 'missing .env'}
            </span>
          </div>
          <div className="flex items-center gap-1">
            <Info className="w-3 h-3" />
            Variables are stored in .env file
          </div>
        </div>
      </div>
    </div>
  );
};
